[2024-03-19T00:13:26.916+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-19T00:13:20.215553+00:00/task_id=load_data_to_db permission to 509
[2024-03-19T00:13:26.951+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-19T00:13:20.215553+00:00/task_id=load_data_to_db permission to 509
[2024-03-19T00:13:26.984+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2024-03-19T00:13:20.215553+00:00 [queued]>
[2024-03-19T00:13:26.993+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2024-03-19T00:13:20.215553+00:00 [queued]>
[2024-03-19T00:13:26.993+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-19T00:13:27.007+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2024-03-19 00:13:20.215553+00:00
[2024-03-19T00:13:27.012+0000] {standard_task_runner.py:57} INFO - Started process 3219 to run task
[2024-03-19T00:13:27.016+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'load_data_to_db', 'manual__2024-03-19T00:13:20.215553+00:00', '--job-id', '59', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpqcvc8ect']
[2024-03-19T00:13:27.017+0000] {standard_task_runner.py:85} INFO - Job 59: Subtask load_data_to_db
[2024-03-19T00:13:27.064+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-19T00:13:20.215553+00:00/task_id=load_data_to_db permission to 509
[2024-03-19T00:13:27.070+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.load_data_to_db manual__2024-03-19T00:13:20.215553+00:00 [running]> on host 3694d3cee1cf
[2024-03-19T00:13:27.152+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-19T00:13:20.215553+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-19T00:13:20.215553+00:00'
[2024-03-19T00:13:27.232+0000] {logging_mixin.py:154} INFO - Success: Loaded 5 recall records to recalls_db.
[2024-03-19T00:13:27.232+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-19T00:13:27.244+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=load_data_to_db, execution_date=20240319T001320, start_date=20240319T001326, end_date=20240319T001327
[2024-03-19T00:13:27.269+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-19T00:13:27.285+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
