[2024-03-18T23:52:31.127+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T23:52:25.138443+00:00/task_id=load_data_to_db permission to 509
[2024-03-18T23:52:31.159+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T23:52:25.138443+00:00/task_id=load_data_to_db permission to 509
[2024-03-18T23:52:31.193+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2024-03-18T23:52:25.138443+00:00 [queued]>
[2024-03-18T23:52:31.203+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: recalls_etl_v1.load_data_to_db manual__2024-03-18T23:52:25.138443+00:00 [queued]>
[2024-03-18T23:52:31.204+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-03-18T23:52:31.219+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): load_data_to_db> on 2024-03-18 23:52:25.138443+00:00
[2024-03-18T23:52:31.224+0000] {standard_task_runner.py:57} INFO - Started process 2893 to run task
[2024-03-18T23:52:31.228+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'recalls_etl_v1', 'load_data_to_db', 'manual__2024-03-18T23:52:25.138443+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/recalls_etl_v1.py', '--cfg-path', '/tmp/tmpvltawx7j']
[2024-03-18T23:52:31.230+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask load_data_to_db
[2024-03-18T23:52:31.277+0000] {logging_mixin.py:154} INFO - Changing /opt/***/logs/dag_id=recalls_etl_v1/run_id=manual__2024-03-18T23:52:25.138443+00:00/task_id=load_data_to_db permission to 509
[2024-03-18T23:52:31.285+0000] {task_command.py:416} INFO - Running <TaskInstance: recalls_etl_v1.load_data_to_db manual__2024-03-18T23:52:25.138443+00:00 [running]> on host 3694d3cee1cf
[2024-03-18T23:52:31.362+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='recalls_etl_v1' AIRFLOW_CTX_TASK_ID='load_data_to_db' AIRFLOW_CTX_EXECUTION_DATE='2024-03-18T23:52:25.138443+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-03-18T23:52:25.138443+00:00'
[2024-03-18T23:52:31.450+0000] {logging_mixin.py:154} INFO - Success: Loaded 5 recall records to recalls_db.
[2024-03-18T23:52:31.451+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-03-18T23:52:31.460+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=recalls_etl_v1, task_id=load_data_to_db, execution_date=20240318T235225, start_date=20240318T235231, end_date=20240318T235231
[2024-03-18T23:52:31.481+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-03-18T23:52:31.498+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
